name: Django_deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull and reload on Aliyun
        run: sshpass -p ${{secrets.PASSWORD}} ssh -o StrictHostKeyChecking=no root@${{secrets.HOST}} "cd ~/academic; python kill.py; git pull --force; git checkout master; python run.py;"